server:
  port: 10000
spring:
  application:
    name: demo-booking-service
  cloud:
    nacos:
      discovery:
        server-addr: 49.232.19.175:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.232.19.175:3307/demo_booking
    username: root
    password: mysql.blueskyan.xyz
